# Generated by Django 3.2.12 on 2022-03-27 13:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change', models.CharField(choices=[('cr', 'Создание'), ('ab', 'Упразднение'), ('rs', 'Переподчинение'), ('rn', 'Переименование'), ('mr', 'Слияние'), ('dv', 'Разделение')], max_length=2, verbose_name='Вид реорганизации')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Дата события')),
                ('event', models.CharField(max_length=64, null=True, verbose_name='Событие')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Описание события')),
                ('search_line', models.CharField(blank=True, help_text='Содержит запись события в нижнем регистре', max_length=254, null=True, verbose_name='Поле для поиска')),
            ],
            options={
                'verbose_name': 'Изменение структуры',
                'verbose_name_plural': 'Структурные изменения',
                'ordering': ['-date', 'change', 'event'],
            },
        ),
        migrations.CreateModel(
            name='OrgUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Полное наименование подразделения', max_length=200, null=True, verbose_name='Наименование')),
                ('short_name', models.CharField(blank=True, help_text='Краткое наименование подразделения', max_length=32, null=True, verbose_name='Аббревиатура')),
                ('structure_code', models.CharField(blank=True, help_text='Код структурного подразделения', max_length=32, null=True, verbose_name='Код')),
                ('type_of_unit', models.CharField(choices=[('dv', 'Обособленное подразделение'), ('of', 'Куратор'), ('bd', 'Орган')], default='dv', help_text='Вид подразделения', max_length=2, verbose_name='Вид')),
                ('date_creation', models.DateField(blank=True, null=True, verbose_name='Дата создания')),
                ('date_abolition', models.DateField(blank=True, null=True, verbose_name='Дата упразднения')),
                ('exist', models.BooleanField(default=True, help_text='Подразделение существует или упразднено?', verbose_name='Статус')),
                ('search_line', models.CharField(blank=True, help_text='Содержит все ключевые поля в нижнем регистре', max_length=254, null=True, verbose_name='Поле для поиска')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='org_unit_parent', to='OrgStructure.orgunit', verbose_name='Подчинение')),
                ('reason_abolition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_unit_abolition', to='OrgStructure.change', verbose_name='Событие')),
                ('reason_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_unit_creation', to='OrgStructure.change', verbose_name='Событие')),
            ],
            options={
                'verbose_name': 'подразделение',
                'verbose_name_plural': 'Подразделения',
                'ordering': ['name'],
                'unique_together': {('name', 'reason_creation')},
            },
        ),
    ]
